### ISSUE TITLE
Change package name

### ISSUE THREAD

**Issue by teemoo7** [benjohnde/play20-pdf#16]
Hi, 
First, thank you for this module, that's a nice job (even if I could not make it work for now).
The module package is `util.pdf.PDF` which is not a very good idea since there already is a `util._` package with Scala (or Java). 

I would thus recommend you to use something like `de.joergviola.play20-pdf.pdf.PDF` instead. This would avoid confusion. 

For example, at some place in my code, I use the `util.Random` classes provided by Scala, which was not working anymore because of course there was no `Random` in the PDF `util` package.

Cheers and thanks

**Comment by benjohnde** [comment]
I changed the package name, but did not release the project yet (maven). But you can download and publish it locally.
