### ISSUE TITLE
/conf/fonts problems while using in production

### ISSUE THREAD

**Issue by spidloun** [benjohnde/play20-pdf#20]
As stated in issue #19, /conf/fonts directory must exist in order to avoid NullPointerException while rendering PDF. This can be fixed with simple check for folder existance. Anyway this issue has other consequences. PDF modules reads fonts directly from filesystem using Java API. This works flawlessly in dev mode using "play run", but if you publish your application to standalone package using "play dist", PDF module is not working anymore. When you create production-ready standalone package, the whole application is merged into the JAR file and every resource must be read through the classloader. Long story short, files are not available through the filesystem calls as desired folders do not exist any more. PDF module than results in NullPointerException every time because it is not able to find folder /conf/fonts. Actually, the feature for auto-loading fonts is unusable at all. The only way to load desired fonts is to use CSS and fetch fonts through the public assets directly from Play application.

**Comment by benjohnde** [comment]
Is now impl'ed.
